# Generated by Django 5.1 on 2024-09-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_customuser_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='bio',
            new_name='whattodo',
        ),
    ]
